# Project
group = dev.tophatcat.projecticbp
mod_name = Project ICBP
mod_id = project_icbp
credits = KiriCattus
license = LGPL-v2.1
license_description = Oh look, a cute friendly penguin... OH! LOOK, A PENGUIN CHARGING AT US!!! Project Intercontinental Ballistic Penguin!
description = Oh look, a cute friendly penguin... OH! LOOK, A PENGUIN CHARGING AT US!!! Project Intercontinental Ballistic Penguin!

# Links
homepage_url = https://tophatcat.dev
discord_url = https://discord.tophatcat.dev
source_url = https://github.com/kiris-mods/project-icbp
issues_url = https://github.com/kiris-mods/project-icbp/issues
license_url = https://github.com/kiris-mods/project-icbp/blob/dev/LICENSE.md

# Common
java_version = 21
minecraft_version = 1.21.11
parchment_minecraft = 1.21.11
parchment_version = 2025.12.20
modrinth_id = 7du8xSpo
curseforge_id = 746338

# NeoForge
# See https://projects.neoforged.net/ for new versions
# See https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
neoforge_version = 21.11.24-beta
neo_form_version = 1.21.11-20251209.172050

moddevgradle_version = 2.0.137

# Fabric
# See https://fabricmc.net/develop/ for new versions
fabric_loom = 1.14.10
fabric_version = 0.140.0
fabric_loader_version = 0.18.3

# Dependencies
# - Common
smart_brain_lib_common_version = 1.16.11
geckolib_common_version = 5.4.1

# - NeoForge
smart_brain_lib_neoforge_version = 1.16.11
geckolib_neoforge_version = 5.4.1
# -- Optional
jade_neoforge_version = 21.0.1

# - Fabric
smart_brain_lib_fabric_version = 1.16.11
geckolib_fabric_version = 5.4.1
# -- Optional
jade_fabric_version = 21.0.1
modmenu_version = 17.0.0-alpha.1

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.debug=false
org.gradle.configuration-cache = false
org.gradle.caching = true
org.gradle.parallel = true
